### ISSUE TITLE
MinizincSolver.solve_sync errors out with `--verbose` extra flags

### ISSUE THREAD

**Issue by juhalehtonen** [bokner/solverl#7]
In the process of trying to debug why I couldn't get MiniZinc to produce results for me, I enabled the `--verbose` extra flag for `MinizincSolver.solve_sync/4`.

The reason this seems to be failing is because eventually the `MinizincModel.model_info/2` tries to decode the `mzn_output` with `Jason`, but fails to do so because the `--verbose` flag(s) will add extra output that makes the data no longer decodeable.

What's your take on how this should be handled by `solverl`?

**Comment by bokner** [comment]
I think that `solverl` should only support essential flags. We don't control MiniZinc output, it may change significantly from one version to another, and its format is often different for different solvers. In particular, `verbose`output would most likely be needed for debugging. If that's the case, then there is an option of extracting the model generated by `solverl` and running it through CLI/IDE with desired flags.
